require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ParkingCodesController do

  # This should return the minimal set of attributes required to create a valid
  # ParkingCode. As you add validations to ParkingCode, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "code" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParkingCodesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all parking_codes as @parking_codes" do
      parking_code = ParkingCode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:parking_codes).should eq([parking_code])
    end
  end

  describe "GET show" do
    it "assigns the requested parking_code as @parking_code" do
      parking_code = ParkingCode.create! valid_attributes
      get :show, {:id => parking_code.to_param}, valid_session
      assigns(:parking_code).should eq(parking_code)
    end
  end

  describe "GET new" do
    it "assigns a new parking_code as @parking_code" do
      get :new, {}, valid_session
      assigns(:parking_code).should be_a_new(ParkingCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested parking_code as @parking_code" do
      parking_code = ParkingCode.create! valid_attributes
      get :edit, {:id => parking_code.to_param}, valid_session
      assigns(:parking_code).should eq(parking_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ParkingCode" do
        expect {
          post :create, {:parking_code => valid_attributes}, valid_session
        }.to change(ParkingCode, :count).by(1)
      end

      it "assigns a newly created parking_code as @parking_code" do
        post :create, {:parking_code => valid_attributes}, valid_session
        assigns(:parking_code).should be_a(ParkingCode)
        assigns(:parking_code).should be_persisted
      end

      it "redirects to the created parking_code" do
        post :create, {:parking_code => valid_attributes}, valid_session
        response.should redirect_to(ParkingCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved parking_code as @parking_code" do
        # Trigger the behavior that occurs when invalid params are submitted
        ParkingCode.any_instance.stub(:save).and_return(false)
        post :create, {:parking_code => { "code" => "invalid value" }}, valid_session
        assigns(:parking_code).should be_a_new(ParkingCode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ParkingCode.any_instance.stub(:save).and_return(false)
        post :create, {:parking_code => { "code" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested parking_code" do
        parking_code = ParkingCode.create! valid_attributes
        # Assuming there are no other parking_codes in the database, this
        # specifies that the ParkingCode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ParkingCode.any_instance.should_receive(:update).with({ "code" => "1" })
        put :update, {:id => parking_code.to_param, :parking_code => { "code" => "1" }}, valid_session
      end

      it "assigns the requested parking_code as @parking_code" do
        parking_code = ParkingCode.create! valid_attributes
        put :update, {:id => parking_code.to_param, :parking_code => valid_attributes}, valid_session
        assigns(:parking_code).should eq(parking_code)
      end

      it "redirects to the parking_code" do
        parking_code = ParkingCode.create! valid_attributes
        put :update, {:id => parking_code.to_param, :parking_code => valid_attributes}, valid_session
        response.should redirect_to(parking_code)
      end
    end

    describe "with invalid params" do
      it "assigns the parking_code as @parking_code" do
        parking_code = ParkingCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ParkingCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => parking_code.to_param, :parking_code => { "code" => "invalid value" }}, valid_session
        assigns(:parking_code).should eq(parking_code)
      end

      it "re-renders the 'edit' template" do
        parking_code = ParkingCode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ParkingCode.any_instance.stub(:save).and_return(false)
        put :update, {:id => parking_code.to_param, :parking_code => { "code" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested parking_code" do
      parking_code = ParkingCode.create! valid_attributes
      expect {
        delete :destroy, {:id => parking_code.to_param}, valid_session
      }.to change(ParkingCode, :count).by(-1)
    end

    it "redirects to the parking_codes list" do
      parking_code = ParkingCode.create! valid_attributes
      delete :destroy, {:id => parking_code.to_param}, valid_session
      response.should redirect_to(parking_codes_url)
    end
  end

end
